apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeseal-certs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
