name: Docker Image CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ilirbekteshi/kubeseal
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t $DOCKER_IMAGE:$GITHUB_SHA -t $DOCKER_IMAGE:latest kubeseal/
        docker push $DOCKER_IMAGE:$GITHUB_SHA
        docker push $DOCKER_IMAGE:latest
